## Scaling-and-Transformation-preprocessing

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
import sklearn

In [2]:
data=pd.read_csv('Travel.csv')

In [3]:
num_col=[fea for fea in data.columns if (data[fea].dtype !='O' and data[fea].dtype !=int)]

num_col

['CustomerID',
 'ProdTaken',
 'Age',
 'CityTier',
 'DurationOfPitch',
 'NumberOfPersonVisiting',
 'NumberOfFollowups',
 'PreferredPropertyStar',
 'NumberOfTrips',
 'Passport',
 'PitchSatisfactionScore',
 'OwnCar',
 'NumberOfChildrenVisiting',
 'MonthlyIncome']

In [4]:
X=data[num_col]

#### Method 1: Standardizing Features

Standardization is the process of centering the variable at zero and standizing the variance to 1.To
standardize the features we subtrsct the mean from each observation and then divide the result by
standard deviation:

z=(x-mean(x))/std(x)

In [6]:
# Performing Mean Imputation
for var in num_col:
    value=X[var].mean()
    X[var]=X[var].fillna(value)

In [7]:
# using sklearn
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
X_scaled=scaler.transform(X)
X_scaled_final=pd.DataFrame(X_scaled)
X_scaled_final

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,-1.731696,2.076787,3.712822e-01,1.468369,-1.143871,0.130966,-0.710021,-0.730127,-1.227404,1.561221,-0.789477,0.782392,-1.393568,-0.500322
1,-1.730988,-0.481513,1.250646e+00,-0.713871,-0.179681,0.130966,0.292203,0.526467,-0.678603,-0.640524,-0.057226,0.782392,0.953955,-0.664693
2,-1.730279,2.076787,-6.839967e-02,-0.713871,-0.902823,0.130966,0.292203,-0.730127,2.065400,1.561221,-0.057226,-1.278132,-1.393568,-1.243704
3,-1.729570,-0.481513,-5.080815e-01,-0.713871,-0.782299,-1.248694,-0.710021,-0.730127,-0.678603,1.561221,1.407276,0.782392,-0.219807,-1.087714
4,-1.728862,-0.481513,-7.810318e-16,-0.713871,-0.902823,-1.248694,-0.710021,0.526467,-1.227404,-0.640524,1.407276,0.782392,-1.393568,-0.981245
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,1.728862,2.076787,1.250646e+00,1.468369,-0.782299,0.130966,1.294428,0.526467,-0.678603,1.561221,-1.521728,0.782392,-0.219807,0.563041
4884,1.729570,2.076787,-1.057684e+00,-0.713871,1.869222,1.510626,1.294428,-0.730127,-0.129803,1.561221,-0.057226,0.782392,0.953955,-0.458610
4885,1.730279,2.076787,1.580407e+00,1.468369,0.181890,1.510626,0.292203,0.526467,2.065400,-0.640524,-1.521728,0.782392,2.127717,1.561836
4886,1.730988,2.076787,-2.046968e+00,1.468369,0.061367,0.130966,0.292203,-0.730127,-0.129803,-0.640524,1.407276,-1.278132,0.953955,-0.634409
4887,1.731696,2.076787,-1.783201e-01,-0.713871,-0.179681,1.510626,0.292203,0.526467,-0.129803,1.561221,-0.057226,0.782392,0.953955,0.080213

#### Method 2: Performing mean normalization

In mean normaliztion ,we center the variable at zero and rescale the distribution to the value range.
This procedure involves subtracting from the mean from each observation and then dividing the
result by the difference between the minimum and maximum values.

x_scaled=(x-mean(x))/(max(x)-min(x))

The transformation results in a distribution centered around 0 ,with min and max values within
the range of -1 to 1

In [10]:
from sklearn.preprocessing import StandardScaler,RobustScaler
scaler_mean=StandardScaler(with_mean=True,with_std=False)# No division by␣standard deviation
scaler_minmax=RobustScaler(with_centering=False,with_scaling=True,quantile_range=(0,100))
scaler_mean.fit(X)
scaler_minmax.fit(X)
X_scaled=scaler_minmax.transform(X)
X_scaled_final=pd.DataFrame(X_scaled)
X_scaled_final

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,40.924903,1.0,0.953488,1.5,0.049180,0.75,0.6,1.5,0.047619,1.0,0.50,1.0,0.000000,0.214920
1,40.925107,0.0,1.139535,0.5,0.114754,0.75,0.8,2.0,0.095238,0.0,0.75,1.0,0.666667,0.206085
2,40.925312,1.0,0.860465,0.5,0.065574,0.75,0.8,1.5,0.333333,1.0,0.75,0.0,0.000000,0.174963
3,40.925517,0.0,0.767442,0.5,0.073770,0.50,0.6,1.5,0.095238,1.0,1.25,1.0,0.333333,0.183347
4,40.925721,0.0,0.874936,0.5,0.065574,0.50,0.6,2.0,0.047619,0.0,1.25,1.0,0.000000,0.189070
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,41.924084,1.0,1.139535,1.5,0.073770,0.75,1.0,2.0,0.095238,1.0,0.25,1.0,0.333333,0.272078
4884,41.924289,1.0,0.651163,0.5,0.254098,1.00,1.0,1.5,0.142857,1.0,0.75,1.0,0.666667,0.217163
4885,41.924494,1.0,1.209302,1.5,0.139344,1.00,0.8,2.0,0.333333,0.0,0.25,1.0,1.000000,0.325764
4886,41.924698,1.0,0.441860,1.5,0.131148,0.75,0.8,1.5,0.142857,0.0,1.25,0.0,0.666667,0.207713
4887,41.924903,1.0,0.837209,0.5,0.114754,1.00,0.8,2.0,0.142857,1.0,0.75,1.0,0.666667,0.246125

#### Method 3: Scaling to the maximum and minimum values

Scaling to the minimum and minimum values squeezes the values of the variables between 0 and 1.

xscaled=(x-min(x))/(max(x)-min(x))

In [11]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X)
X_scaled=scaler.transform(X)
X_scaled_final=pd.DataFrame(X_scaled)
X_scaled_final

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.000000,1.0,0.534884,1.0,0.008197,0.50,0.4,0.0,0.000000,1.0,0.25,1.0,0.000000,0.204683
1,0.000205,0.0,0.720930,0.0,0.073770,0.50,0.6,0.5,0.047619,0.0,0.50,1.0,0.666667,0.195848
2,0.000409,1.0,0.441860,0.0,0.024590,0.50,0.6,0.0,0.285714,1.0,0.50,0.0,0.000000,0.164725
3,0.000614,0.0,0.348837,0.0,0.032787,0.25,0.4,0.0,0.047619,1.0,1.00,1.0,0.333333,0.173110
4,0.000818,0.0,0.456332,0.0,0.024590,0.25,0.4,0.5,0.000000,0.0,1.00,1.0,0.000000,0.178832
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,0.999182,1.0,0.720930,1.0,0.032787,0.50,0.8,0.5,0.047619,1.0,0.00,1.0,0.333333,0.261840
4884,0.999386,1.0,0.232558,0.0,0.213115,0.75,0.8,0.0,0.095238,1.0,0.50,1.0,0.666667,0.206925
4885,0.999591,1.0,0.790698,1.0,0.098361,0.75,0.6,0.5,0.285714,0.0,0.00,1.0,1.000000,0.315527
4886,0.999795,1.0,0.023256,1.0,0.090164,0.50,0.6,0.0,0.095238,0.0,1.00,0.0,0.666667,0.197475
4887,1.000000,1.0,0.418605,0.0,0.073770,0.75,0.6,0.5,0.095238,1.0,0.50,1.0,0.666667,0.235887

#### Method 4: Implementing Maximum absolute scaling

xscaled=x/max(x)

In [12]:
from sklearn.preprocessing import MaxAbsScaler
scaler=MaxAbsScaler()
scaler.fit(X)
X_scaled=scaler.transform(X)
X_scaled_final=pd.DataFrame(X_scaled)
X_scaled_final

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.976148,1.0,0.672131,1.000000,0.047244,0.6,0.500000,0.6,0.045455,1.0,0.4,1.0,0.000000,0.212742
1,0.976153,0.0,0.803279,0.333333,0.110236,0.6,0.666667,0.8,0.090909,0.0,0.6,1.0,0.666667,0.203997
2,0.976158,1.0,0.606557,0.333333,0.062992,0.6,0.666667,0.6,0.318182,1.0,0.6,0.0,0.000000,0.173190
3,0.976162,0.0,0.540984,0.333333,0.070866,0.4,0.500000,0.6,0.090909,1.0,1.0,1.0,0.333333,0.181489
4,0.976167,0.0,0.616758,0.333333,0.062992,0.4,0.500000,0.8,0.045455,0.0,1.0,1.0,0.000000,0.187154
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,0.999980,1.0,0.803279,1.000000,0.070866,0.6,0.833333,0.8,0.090909,1.0,0.2,1.0,0.333333,0.269320
4884,0.999985,1.0,0.459016,0.333333,0.244094,0.8,0.833333,0.6,0.136364,1.0,0.6,1.0,0.666667,0.214962
4885,0.999990,1.0,0.852459,1.000000,0.133858,0.8,0.666667,0.8,0.318182,0.0,0.2,1.0,1.000000,0.322463
4886,0.999995,1.0,0.311475,1.000000,0.125984,0.6,0.666667,0.6,0.136364,0.0,1.0,0.0,0.666667,0.205608
4887,1.000000,1.0,0.590164,0.333333,0.110236,0.8,0.666667,0.8,0.136364,1.0,0.6,1.0,0.666667,0.243631

**Method 5: Scaling with median and Quantiles**

xscaled= (x-median(x))/(q3(x)-q1(x))

In [13]:
scaler=RobustScaler()
scaler.fit(X)
X_scaled=scaler.transform(X)
X_scaled_final=pd.DataFrame(X_scaled)
X_scaled_final

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,-1.000000,1.0,0.333333,1.0,-0.8,0.0,-1.0,0.0,-1.0,1.0,-0.5,0.0,-1.0,-0.336454
1,-0.999591,0.0,1.000000,0.0,0.0,0.0,0.0,1.0,-0.5,0.0,0.0,0.0,1.0,-0.511159
2,-0.999182,1.0,0.000000,0.0,-0.6,0.0,0.0,0.0,2.0,1.0,0.0,-1.0,-1.0,-1.126575
3,-0.998772,0.0,-0.333333,0.0,-0.5,-1.0,-1.0,0.0,-0.5,1.0,1.0,0.0,0.0,-0.960777
4,-0.998363,0.0,0.051855,0.0,-0.6,-1.0,-1.0,1.0,-1.0,0.0,1.0,0.0,-1.0,-0.847614
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,0.998363,1.0,1.000000,1.0,-0.5,0.0,1.0,1.0,-0.5,1.0,-1.0,0.0,0.0,0.793765
4884,0.998772,1.0,-0.750000,0.0,1.7,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,-0.292120
4885,0.999182,1.0,1.250000,1.0,0.3,1.0,0.0,1.0,2.0,0.0,-1.0,0.0,2.0,1.855357
4886,0.999591,1.0,-1.500000,1.0,0.2,0.0,0.0,0.0,0.0,0.0,1.0,-1.0,1.0,-0.478972
4887,1.000000,1.0,-0.083333,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.280581

#### Method 6: Scaling to vector unit length

xscaled =x/norm

where norm may be either Manhattan distance or Euclidean Distance

In [14]:
from sklearn.preprocessing import Normalizer
scaler=Normalizer(norm='l2')# l2 for Euclidean Distance
scaler.fit(X)
X_scaled=scaler.transform(X)
X_scaled_final=pd.DataFrame(X_scaled)
X_scaled_final

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.994536,0.000005,0.000204,0.000015,0.000030,0.000015,0.000015,0.000015,0.000005,0.000005,0.000010,0.000005,0.000000,0.104391
1,0.994973,0.000000,0.000244,0.000005,0.000070,0.000015,0.000020,0.000020,0.000010,0.000000,0.000015,0.000005,0.000010,0.100144
2,0.996369,0.000005,0.000184,0.000005,0.000040,0.000015,0.000020,0.000015,0.000035,0.000005,0.000015,0.000000,0.000000,0.085139
3,0.996015,0.000000,0.000164,0.000005,0.000045,0.000010,0.000015,0.000015,0.000010,0.000005,0.000025,0.000005,0.000005,0.089187
4,0.995764,0.000000,0.000187,0.000005,0.000040,0.000010,0.000015,0.000020,0.000005,0.000000,0.000025,0.000005,0.000000,0.091947
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,0.991692,0.000005,0.000237,0.000015,0.000044,0.000015,0.000024,0.000019,0.000010,0.000005,0.000005,0.000005,0.000005,0.128635
4884,0.994683,0.000005,0.000136,0.000005,0.000151,0.000019,0.000024,0.000015,0.000015,0.000005,0.000015,0.000005,0.000010,0.102981
4885,0.988154,0.000005,0.000251,0.000014,0.000082,0.000019,0.000019,0.000019,0.000034,0.000000,0.000005,0.000005,0.000014,0.153467
4886,0.995133,0.000005,0.000092,0.000015,0.000078,0.000015,0.000019,0.000015,0.000015,0.000000,0.000024,0.000000,0.000010,0.098544
4887,0.993186,0.000005,0.000175,0.000005,0.000068,0.000019,0.000019,0.000019,0.000015,0.000005,0.000015,0.000005,0.000010,0.116538